import { AlgorithmPreset } from './types';

export const ALGORITHM_PRESETS: AlgorithmPreset[] = [
  {
    name: 'Bell State',
    description: 'Creates maximally entangled |Φ⁺⟩ = (|00⟩ + |11⟩)/√2',
    numQubits: 2,
    category: 'basic',
    gates: [
      { type: 'H', wireIndex: 0, position: 0 },
      { type: 'CNOT', wireIndex: 1, position: 1, controlWire: 0 },
    ],
  },
  {
    name: 'GHZ State',
    description: '3-qubit entangled state (|000⟩ + |111⟩)/√2',
    numQubits: 3,
    category: 'basic',
    gates: [
      { type: 'H', wireIndex: 0, position: 0 },
      { type: 'CNOT', wireIndex: 1, position: 1, controlWire: 0 },
      { type: 'CNOT', wireIndex: 2, position: 2, controlWire: 1 },
    ],
  },
  {
    name: "Grover's (2-qubit)",
    description: 'Quantum search amplifying |11⟩ state',
    numQubits: 2,
    category: 'basic',
    gates: [
      { type: 'H', wireIndex: 0, position: 0 },
      { type: 'H', wireIndex: 1, position: 0 },
      { type: 'Z', wireIndex: 0, position: 1 },
      { type: 'Z', wireIndex: 1, position: 1 },
      { type: 'H', wireIndex: 0, position: 2 },
      { type: 'H', wireIndex: 1, position: 2 },
      { type: 'X', wireIndex: 0, position: 3 },
      { type: 'X', wireIndex: 1, position: 3 },
      { type: 'H', wireIndex: 1, position: 4 },
      { type: 'CNOT', wireIndex: 1, position: 5, controlWire: 0 },
      { type: 'H', wireIndex: 1, position: 6 },
      { type: 'X', wireIndex: 0, position: 7 },
      { type: 'X', wireIndex: 1, position: 7 },
      { type: 'H', wireIndex: 0, position: 8 },
      { type: 'H', wireIndex: 1, position: 8 },
    ],
  },
  {
    name: 'Superposition',
    description: 'Equal superposition of all basis states',
    numQubits: 3,
    category: 'basic',
    gates: [
      { type: 'H', wireIndex: 0, position: 0 },
      { type: 'H', wireIndex: 1, position: 0 },
      { type: 'H', wireIndex: 2, position: 0 },
    ],
  },
  {
    name: '3-Bit Flip Code',
    description: 'Error correction: encodes 1 logical qubit in 3 physical qubits',
    numQubits: 3,
    category: 'error-correction',
    gates: [
      { type: 'CNOT', wireIndex: 1, position: 0, controlWire: 0 },
      { type: 'CNOT', wireIndex: 2, position: 1, controlWire: 0 },
      { type: 'CNOT', wireIndex: 1, position: 3, controlWire: 0 },
      { type: 'CNOT', wireIndex: 2, position: 4, controlWire: 1 },
      { type: 'CNOT', wireIndex: 0, position: 5, controlWire: 1 },
    ],
  },
  {
    name: 'VQE (H₂)',
    description: 'Variational Quantum Eigensolver ansatz for H₂ molecule',
    numQubits: 2,
    category: 'variational',
    gates: [
      { type: 'X', wireIndex: 0, position: 0 },
      { type: 'H', wireIndex: 0, position: 1 },
      { type: 'H', wireIndex: 1, position: 1 },
      { type: 'CNOT', wireIndex: 1, position: 2, controlWire: 0 },
      { type: 'RZ', wireIndex: 1, position: 3, parameter: Math.PI / 4 },
      { type: 'CNOT', wireIndex: 1, position: 4, controlWire: 0 },
      { type: 'H', wireIndex: 0, position: 5 },
      { type: 'H', wireIndex: 1, position: 5 },
    ],
  },
  {
    name: 'VQE (HeH⁺)',
    description: 'VQE ansatz for HeH⁺ with 3 qubits',
    numQubits: 3,
    category: 'variational',
    gates: [
      { type: 'X', wireIndex: 0, position: 0 },
      { type: 'X', wireIndex: 1, position: 0 },
      { type: 'H', wireIndex: 0, position: 1 },
      { type: 'CNOT', wireIndex: 1, position: 2, controlWire: 0 },
      { type: 'CNOT', wireIndex: 2, position: 3, controlWire: 1 },
      { type: 'RZ', wireIndex: 0, position: 4, parameter: Math.PI / 4 },
      { type: 'RZ', wireIndex: 1, position: 4, parameter: Math.PI / 2 },
      { type: 'RZ', wireIndex: 2, position: 4, parameter: Math.PI / 4 },
      { type: 'CNOT', wireIndex: 2, position: 5, controlWire: 0 },
      { type: 'H', wireIndex: 1, position: 6 },
    ],
  },
  {
    name: 'QAOA (MaxCut)',
    description: 'QAOA for 2-node MaxCut: finds optimal graph partition',
    numQubits: 2,
    category: 'variational',
    gates: [
      { type: 'H', wireIndex: 0, position: 0 },
      { type: 'H', wireIndex: 1, position: 0 },
      { type: 'CNOT', wireIndex: 1, position: 1, controlWire: 0 },
      { type: 'RZ', wireIndex: 1, position: 2, parameter: Math.PI / 4 },
      { type: 'CNOT', wireIndex: 1, position: 3, controlWire: 0 },
      { type: 'H', wireIndex: 0, position: 4 },
      { type: 'H', wireIndex: 1, position: 4 },
      { type: 'RZ', wireIndex: 0, position: 5, parameter: Math.PI / 4 },
      { type: 'RZ', wireIndex: 1, position: 5, parameter: Math.PI / 4 },
      { type: 'H', wireIndex: 0, position: 6 },
      { type: 'H', wireIndex: 1, position: 6 },
    ],
  },
  {
    name: 'QAOA (Triangle)',
    description: 'QAOA for 3-node triangle graph MaxCut',
    numQubits: 3,
    category: 'variational',
    gates: [
      { type: 'H', wireIndex: 0, position: 0 },
      { type: 'H', wireIndex: 1, position: 0 },
      { type: 'H', wireIndex: 2, position: 0 },
      { type: 'CNOT', wireIndex: 1, position: 1, controlWire: 0 },
      { type: 'RZ', wireIndex: 1, position: 2, parameter: Math.PI / 4 },
      { type: 'CNOT', wireIndex: 1, position: 3, controlWire: 0 },
      { type: 'CNOT', wireIndex: 2, position: 4, controlWire: 1 },
      { type: 'RZ', wireIndex: 2, position: 5, parameter: Math.PI / 4 },
      { type: 'CNOT', wireIndex: 2, position: 6, controlWire: 1 },
      { type: 'H', wireIndex: 0, position: 7 },
      { type: 'H', wireIndex: 1, position: 7 },
      { type: 'H', wireIndex: 2, position: 7 },
      { type: 'RZ', wireIndex: 0, position: 8, parameter: Math.PI / 4 },
      { type: 'RZ', wireIndex: 1, position: 8, parameter: Math.PI / 4 },
      { type: 'RZ', wireIndex: 2, position: 8, parameter: Math.PI / 4 },
      { type: 'H', wireIndex: 0, position: 9 },
      { type: 'H', wireIndex: 1, position: 9 },
      { type: 'H', wireIndex: 2, position: 9 },
    ],
  },
];
